-- 없어진 기록 찾기 https://programmers.co.kr/learn/courses/30/lessons/59042
SELECT o.ANIMAL_ID, o.NAME 
FROM ANIMAL_INS i
RIGHT JOIN ANIMAL_OUTS o
ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE i.ANIMAL_ID is NULL;

-- MySQL은 FULL OUTER JOIN이 없다
-- 다음과 같이 실행한다
SELECT i.ANIMAL_ID, i.NAME 
FROM ANIMAL_INS i
LEFT JOIN ANIMAL_OUTS o
ON i.ANIMAL_ID = o.ANIMAL_ID
UNION
SELECT i.ANIMAL_ID, i.NAME 
FROM ANIMAL_INS i
RIGHT JOIN ANIMAL_OUTS o
ON i.ANIMAL_ID = o.ANIMAL_ID;
